# Pixel-by-pixel masters transcribed from the supplied pet design boards.
#
# Every entry below is an explicit x coordinate plus a semantic pixel run on a
# 30x30 authoring area. No reference bitmap is opened, cropped, sampled, or
# rescaled by this source file. The runtime compiler maps these cells directly
# into the fixed 32x32 sprite atlas.

function New-ReferenceRows([int]$width, [object[]]$rows) {
    $result = [System.Collections.Generic.List[string]]::new()
    foreach ($row in $rows) {
        $x = [int]$row[0]
        $pixels = [string]$row[1]
        if ($x -lt 0 -or ($x + $pixels.Length) -gt $width) {
            throw "Reference pixel run is outside the $width-pixel artboard: x=$x, run=$pixels"
        }
        $result.Add(("." * $x) + $pixels + ("." * ($width - $x - $pixels.Length)))
    }
    return @($result)
}

function Get-PixelPetReferenceMaster([string]$species, [int]$stage) {
    $key = "$species/$stage"
    switch ($key) {
        # Cat: striped cream egg, side-on kitten, seated cat, fluffy high form.
        'cat/0' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'ooccccoo'),
            @(10, 'occhhccco'),
            @(9, 'occcaaaccco'),
            @(8, 'occcaaaacccco'),
            @(7, 'occcccccccccco'),
            @(7, 'occaacccccccco'),
            @(6, 'ocaaaacccccccco'),
            @(6, 'occaacccccccco'),
            @(6, 'occcccccaaaccco'),
            @(6, 'occcccccaaaaccco'),
            @(7, 'occcccccaaaccco'),
            @(6, 'occcccccccccccco'),
            @(7, 'occccccccccccco'),
            @(7, 'occhccccccccco'),
            @(8, 'occccccccccco'),
            @(9, 'occcccccccco'),
            @(10, 'ooccccccoo'),
            @(12, 'oooooooo')
        ) }
        'cat/1' { return New-ReferenceRows 30 @(
            @(19, 'oo.oo'),
            @(18, 'obobbo'),
            @(17, 'obbbbbo'),
            @(16, 'obcccbbo'),
            @(5, 'oo........obcecebbo'),
            @(4, 'obbo.......obcacbbo'),
            @(3, 'ob.boo....obbbbbbo'),
            @(3, 'ob...ooooobbbbbbo'),
            @(4, 'oo...obbbbbbbbbo'),
            @(9, 'obbbbbbbbo'),
            @(9, 'obbboobbbbo'),
            @(9, 'obbo..obbo'),
            @(10, 'oo....oo')
        ) }
        'cat/2' { return New-ReferenceRows 30 @(
            @(10, 'oo..........oo'),
            @(9, 'obbo........obbo'),
            @(8, 'obbbo......obbbo'),
            @(8, 'obbbbbbbbbbbbbbo'),
            @(7, 'obbbssssssssbbbbo'),
            @(7, 'obbbssbbbbssbbbbo'),
            @(6, 'obbbcceccceccbbbbo'),
            @(5, 'ooobbbccccaccccbbbooo'),
            @(6, 'obbbcccaaacccbbbbo'),
            @(7, 'obbbbccccccccbbbbo'),
            @(8, 'obbbbbbbbbbbbbbo'),
            @(9, 'obbbbbbbbbbbbo'),
            @(5, 'oo..obbbbbbbbbbbbo'),
            @(4, 'obbo.obbbssbbbbbbbbo'),
            @(3, 'obbbobbbbssbbbbbbbbo'),
            @(3, 'obboobbbbbbbbccccbbbo'),
            @(4, 'oo.obbbbbbbbbccccbbbo'),
            @(7, 'obbbbbbbbbccccbbbo'),
            @(7, 'obbbbbbbbbccccbbbo'),
            @(7, 'obbbbbbbbbbbbbbbbo'),
            @(8, 'obbbbbbbbbbbbbbo'),
            @(9, 'obbbboobbbbbo'),
            @(9, 'obbbboobbbbbo'),
            @(10, 'obbbo..obbbo'),
            @(10, 'obbo....obbo'),
            @(9, 'oosso....osso')
        ) }
        'cat/3' { return New-ReferenceRows 30 @(
            @(11, 'oo........oo'),
            @(10, 'obbo......obbo'),
            @(9, 'obbbo....obbbo'),
            @(8, 'obbbbbbbbbbbbbo'),
            @(7, 'obbbssssssssbbbbo'),
            @(7, 'obbbssbbbbssbbbbo'),
            @(6, 'obbbcceccceccbbbbo'),
            @(5, 'ooobbbccccaccccbbbooo'),
            @(6, 'obbbcccaaacccbbbbo'),
            @(7, 'obbbbccccccccbbbbo'),
            @(8, 'obbbbbbbbbbbbbbo'),
            @(6, 'oobbbbbbbbbbbbboo'),
            @(3, 'oo.obbbbbbbbbbbbbbo'),
            @(2, 'obboobbbbssbbbbbbbbo'),
            @(1, 'obbbobbbbbssbbbbbbbbo'),
            @(1, 'obboobbbbbbbbccccbbbbo'),
            @(2, 'obobbbbbbbbbccccbbbbo'),
            @(2, 'obbbbbbbbbbbccccbbbbo'),
            @(3, 'obbbbbbbbbbbccccbbbo'),
            @(3, 'obbbbbbbbbbbbbbbbbbo'),
            @(4, 'obbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbo'),
            @(6, 'obbbbboobbbbbo'),
            @(6, 'obbbbboobbbbbo'),
            @(7, 'obbbbo..obbbbo'),
            @(7, 'obbo....obbo'),
            @(6, 'oosssso..osssso'),
            @(7, 'oooooo....oooooo')
        ) }

        # Dog: warm face egg and a Shiba-like curled-tail silhouette.
        'dog/0' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'ooccccoo'),
            @(10, 'occcccccco'),
            @(9, 'occcbbbbccco'),
            @(8, 'occbbssbbccco'),
            @(7, 'occbccccccbcco'),
            @(7, 'ocbcccececccbco'),
            @(6, 'ocbbcccaccccbbco'),
            @(6, 'ocbbccccccccbbco'),
            @(6, 'occcbbbccbbbccco'),
            @(6, 'occcccbbbbccccco'),
            @(6, 'occcccccccccccco'),
            @(7, 'occcccccccccco'),
            @(7, 'occhccccccccco'),
            @(8, 'occccccccccco'),
            @(9, 'occcccccccco'),
            @(10, 'ooccccccoo'),
            @(12, 'oooooooo')
        ) }
        'dog/1' { return New-ReferenceRows 30 @(
            @(17, 'oooo..ooo'),
            @(16, 'obbbboobbo'),
            @(16, 'obbbbbbbbo'),
            @(15, 'obccccbbbbo'),
            @(5, 'ooo......obcececbbo'),
            @(4, 'obboo.....obcacccbbo'),
            @(3, 'ob.oboo...obbbbbbbbo'),
            @(3, 'ob...oobbbbbbbbbbo'),
            @(4, 'oo....obbbbbbbbbo'),
            @(9, 'obbbbbbbbo'),
            @(9, 'obbboobbbbo'),
            @(9, 'obbo..obbo'),
            @(10, 'oo....oo')
        ) }
        'dog/2' { return New-ReferenceRows 30 @(
            @(17, 'ooo......ooo'),
            @(16, 'obbbbo...obbo'),
            @(15, 'obbbbbbo.obbbbo'),
            @(14, 'obbbbbbbbbbbbbo'),
            @(13, 'obbbbssssssbbbbo'),
            @(13, 'obbbssbbbbssbbbo'),
            @(12, 'obbbcceccceccbbbbo'),
            @(8, 'ooobbbccccaccccbbbooo'),
            @(12, 'obbbcccaaacccbbbbo'),
            @(13, 'obbbbbccccccbbbbo'),
            @(14, 'obbbbbbbbbbbbbo'),
            @(4, 'ooo......obbbbbbbbbbbbo'),
            @(3, 'obboo...obbbbrrrrbbbbbbbo'),
            @(2, 'ob.oboo.obbbbrrhrrbbbbbbbbo'),
            @(2, 'ob...ooobbbbbbbbbbbbbbbbbo'),
            @(3, 'oo....obbbbbbbbbbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbbbbbo'),
            @(8, 'obbboobbbboobbbbo'),
            @(8, 'obbbo.obbbbo.obbbo'),
            @(9, 'obbo..obbo..obbo'),
            @(9, 'oao...oao...oao'),
            @(8, 'osso..osso..osso')
        ) }
        'dog/3' { return New-ReferenceRows 30 @(
            @(15, 'ooo......ooo'),
            @(14, 'obbbbo...obbo'),
            @(12, 'obbbbbbo.obbbbo'),
            @(12, 'obbbbbbbbbbbbbo'),
            @(11, 'obbbbssssssbbbbo'),
            @(11, 'obbbssbbbbssbbbo'),
            @(9, 'obbbcceccceccbbbbo'),
            @(6, 'ooobbbccccaccccbbbooo'),
            @(9, 'obbbcccaaacccbbbbo'),
            @(10, 'obbbbbccccccbbbbo'),
            @(12, 'obbbbbbbbbbbbbo'),
            @(4, 'oooo.....obbbbbbbbbbbbo'),
            @(2, 'oobbbbo..obbbbssssbbbbbbbo'),
            @(1, 'obboobbo.obbbbssssbbbbbbbbo'),
            @(0, 'obbo..ooobbbbrrrrrrbbbbbbbbo'),
            @(0, 'obbo...obbbbbrrhrrrbbbbbbbbo'),
            @(1, 'oo....obbbbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbbbbbbbo'),
            @(6, 'obbbboobbbbboobbbbbo'),
            @(6, 'obbbboobbbbboobbbbbo'),
            @(7, 'obbbo..obbbbo..obbbo'),
            @(7, 'obbo...obbbbo...obbo'),
            @(7, 'oao....oao.....oao'),
            @(6, 'osso...osso.....osso')
        ) }

        # Bird: blue spotted egg, yellow chick, perched blue bird, winged form.
        'bird/0' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'oobbbboo'),
            @(10, 'obbbbbbbbo'),
            @(9, 'obbbhbbbbbo'),
            @(8, 'obbbbbbbbbbo'),
            @(7, 'obbbbrbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbo'),
            @(6, 'obbhbbbbbbbbbbbo'),
            @(6, 'obbbbbbrbbbbbbbo'),
            @(6, 'obbbbbbbbbbbbbbo'),
            @(6, 'obbbhbbbbhbbbbo'),
            @(6, 'obbbbbbbbbbbbbbo'),
            @(7, 'obbbbrbbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbo'),
            @(8, 'obbhbbbbbbbbo'),
            @(8, 'obbbbbbbbbbo'),
            @(9, 'obbbbbbbbbo'),
            @(10, 'obbbbbbbo'),
            @(11, 'oobbbboo'),
            @(13, 'oooo')
        ) }
        'bird/1' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'oocccboo'),
            @(10, 'occcccbbo'),
            @(9, 'occecccbbbo'),
            @(8, 'occccccaabbbo'),
            @(7, 'occcccccabbbbbo'),
            @(6, 'obccccccbbbbbbbo'),
            @(6, 'obbbccccbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbo'),
            @(8, 'obbbbbbbbbo'),
            @(9, 'obbbbbbo'),
            @(9, 'obbboobbo'),
            @(10, 'oao..oao')
        ) }
        'bird/2' { return New-ReferenceRows 30 @(
            @(16, 'oooooo'),
            @(14, 'oobbbbbboo'),
            @(13, 'obbbbbbbbbbo'),
            @(12, 'obbbbbeeccbo'),
            @(11, 'obbbbbccccabbo'),
            @(10, 'obbbbbbccccaaa'),
            @(8, 'oobbbbbbbccccbo'),
            @(6, 'obbbbbbbbbccccbo'),
            @(5, 'obbbbbbbbbbccccbo'),
            @(5, 'obbbbssbbbbccccbo'),
            @(6, 'obbbbsssbbbbccbo'),
            @(7, 'obbbbsssbbbbbo'),
            @(8, 'obbbbbbbbbbo'),
            @(9, 'obbbbbbbbbo'),
            @(10, 'obbbbbbbo'),
            @(11, 'obbbbbo'),
            @(10, 'obbo'),
            @(9, 'obboooooooooooo'),
            @(7, 'oobbbbbbbbbbbbbboo'),
            @(8, 'oooooooooooooooo')
        ) }
        'bird/3' { return New-ReferenceRows 30 @(
            @(1, 'oo.........................oo'),
            @(0, 'obbo......................obbo'),
            @(0, 'obbbo........oooo........obbbo'),
            @(0, 'obbbbbo....oobbbboo....obbbbbo'),
            @(0, 'obbbbbbbo.obbbbbbbbo.obbbbbbbo'),
            @(0, 'obbbbbbbboobbbbbbbboobbbbbbbbo'),
            @(1, 'obbbrrbbbbbbbbbbbbbbbbrrbbbo'),
            @(0, 'obbbrrrbbbbbbbeccbbbbbbrrrbbo'),
            @(0, 'obbbrrrrbbbbbbcccabbbbbrrrrbbo'),
            @(0, 'obbbbrrrbbbbbbcccabbbbbrrrbbbo'),
            @(0, 'oobbbbrrbbbbbbbbbbbbbbrrbbbboo'),
            @(0, 'obbbbbbbbbbbbbbbbbbbbbbbbbbbbo'),
            @(1, 'obbbbbbbbbbbbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbbbbbbbbbbo'),
            @(8, 'obbbbbbbbbbbbbbbbo'),
            @(10, 'obbbbbbbbbbbbo'),
            @(11, 'obbbbbbbbbbo'),
            @(11, 'obbbccccbbbo'),
            @(10, 'obbbccccccbbbo'),
            @(10, 'obbbbbbbbbbbbo'),
            @(10, 'obbbboobbbbbo'),
            @(9, 'obbbo..obbbo'),
            @(8, 'obbooooooobbo'),
            @(7, 'oobbbbbbbbbboo'),
            @(8, 'oooooooooooo')
        ) }

        # Penguin: face-and-scarf egg, downy chick, round adult, crowned form.
        'penguin/0' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'oossssoo'),
            @(10, 'osssssssso'),
            @(9, 'ossccccssso'),
            @(8, 'ossceeccecsso'),
            @(7, 'osssccccccsssso'),
            @(7, 'ossssaaaacsssso'),
            @(6, 'osssssccccssssso'),
            @(6, 'osssssrrrrssssso'),
            @(6, 'ossssrhrhrssssso'),
            @(6, 'osssssrrrrssssso'),
            @(6, 'osssssssssssssso'),
            @(7, 'ossssccccssssso'),
            @(7, 'ossssccccssssso'),
            @(8, 'osssssssssssso'),
            @(9, 'osssssssssso'),
            @(10, 'oossssssoo'),
            @(12, 'oooooooo')
        ) }
        'penguin/1' { return New-ReferenceRows 30 @(
            @(12, 'oooooo'),
            @(10, 'oossssssoo'),
            @(9, 'osssssssssso'),
            @(9, 'osssccccssso'),
            @(8, 'osssceeccecssso'),
            @(8, 'ossssccacccssso'),
            @(7, 'ossssssccccssssso'),
            @(6, 'osssssccccccssssso'),
            @(5, 'oosssssccccccsssssoo'),
            @(6, 'osssssrrrrrrssssso'),
            @(7, 'ossssrhrhrssssso'),
            @(8, 'osssssssssssso'),
            @(9, 'ossssccccsssso'),
            @(10, 'osss....ssso'),
            @(10, 'oao....oao')
        ) }
        'penguin/2' { return New-ReferenceRows 30 @(
            @(11, 'oooooooooo'),
            @(9, 'oossssssssssoo'),
            @(8, 'ossssssssssssso'),
            @(7, 'ossssccccccssssso'),
            @(6, 'osssscccececcssssso'),
            @(6, 'ossssccccacccssssso'),
            @(5, 'ossssssccccccssssssso'),
            @(4, 'osssssssccccccsssssssso'),
            @(3, 'oosssssssccccccssssssssoo'),
            @(2, 'ossssssssccccccssssssssso'),
            @(3, 'ossssssssccccccsssssssso'),
            @(4, 'osssssssrrrrrrrrsssssssso'),
            @(4, 'ossssssrhrhrhrhrsssssssso'),
            @(4, 'osssssssrrrrrrrrsssssssso'),
            @(4, 'osssssssssssssssssssssso'),
            @(5, 'osssssssccccccsssssssso'),
            @(6, 'osssssccccccccssssso'),
            @(7, 'osssssccccccccsssso'),
            @(8, 'osssssssssssssso'),
            @(9, 'osssssssssssso'),
            @(10, 'ossss....sssso'),
            @(10, 'oaaaa....aaaao'),
            @(10, 'oooooo..oooooo')
        ) }
        'penguin/3' { return New-ReferenceRows 30 @(
            @(12, 'a.a.a'),
            @(11, 'aaaaaaa'),
            @(12, 'aaaaa'),
            @(10, 'oooooooooo'),
            @(8, 'oossssssssssoo'),
            @(7, 'ossssssssssssso'),
            @(6, 'osssssccccssssssso'),
            @(6, 'osssscccececssssso'),
            @(6, 'ossssscccacccssssso'),
            @(5, 'osssssssccccsssssssso'),
            @(4, 'ossssssssccccssssssssso'),
            @(3, 'oosssssssccccsssssssssoo'),
            @(2, 'ossssssssccccssssssssssso'),
            @(3, 'osssssssrrrrrrrrsssssssso'),
            @(3, 'ossssssrhrhrhrhrsssssssso'),
            @(3, 'osssssssrrrrrrrrsssssssso'),
            @(4, 'osssssssssssssssssssssso'),
            @(5, 'ossssssccccccccssssssso'),
            @(6, 'osssssccccccccssssso'),
            @(7, 'osssssssssssssssso'),
            @(8, 'ossssssssssssso'),
            @(9, 'ossss....ssssso'),
            @(9, 'oaaaa....aaaao'),
            @(10, 'oooo......oooo')
        ) }

        # Rabbit: pink-marked egg and long-eared, white/pink silhouettes.
        'rabbit/0' { return New-ReferenceRows 30 @(
            @(13, 'oooo'),
            @(11, 'ooccccoo'),
            @(10, 'occmccccco'),
            @(9, 'occmmmccccco'),
            @(8, 'occcmmcccccco'),
            @(7, 'occcccccccccco'),
            @(7, 'occcccmmmccccco'),
            @(6, 'occcccmmmmccccco'),
            @(6, 'occcccmmmmccccco'),
            @(6, 'occcccccmmccccco'),
            @(6, 'occmccccccccmcco'),
            @(6, 'occcccccccccccco'),
            @(7, 'occcccmmmccccco'),
            @(7, 'occccccmcccccco'),
            @(8, 'occccccccccco'),
            @(9, 'occcccccccco'),
            @(10, 'ooccccccoo'),
            @(12, 'oooooooo')
        ) }
        'rabbit/1' { return New-ReferenceRows 30 @(
            @(9, 'oo.oo'),
            @(8, 'ocmocmo'),
            @(8, 'ocmocmo'),
            @(7, 'occccccbo'),
            @(6, 'occececcbbo'),
            @(6, 'occcacccccbbo'),
            @(7, 'occccccccccbbooo'),
            @(8, 'occcccccccccobbo'),
            @(9, 'occccccccccco.oo'),
            @(10, 'occcccccccbo'),
            @(10, 'occcoocccco'),
            @(11, 'occo..occo'),
            @(11, 'oao....oao')
        ) }
        'rabbit/2' { return New-ReferenceRows 30 @(
            @(10, 'oo.....oo'),
            @(9, 'ommo...ommo'),
            @(9, 'ommo...ommo'),
            @(9, 'osso...osso'),
            @(9, 'osso...osso'),
            @(8, 'occcooocccco'),
            @(7, 'occcccccccccco'),
            @(6, 'occcscececccccbo'),
            @(5, 'occcssxccccccccbbo'),
            @(5, 'occcccacccccccccbo'),
            @(6, 'occcccccccccbo'),
            @(8, 'oocccccccboo'),
            @(10, 'occcccccbo'),
            @(9, 'occcccccccccbo'),
            @(8, 'occcccccccccccbo'),
            @(7, 'occcccccccccccccbooo'),
            @(7, 'occcccccccccccccosso'),
            @(8, 'occcccccccccccccosso'),
            @(9, 'occcccccccccccccsoo'),
            @(10, 'occcccccccccccco'),
            @(10, 'occcccccccccccbo'),
            @(9, 'occccooocccccco'),
            @(8, 'occcco...occcco'),
            @(9, 'occo.....occo'),
            @(9, 'oao.......oao')
        ) }
        'rabbit/3' { return New-ReferenceRows 30 @(
            @(10, 'oo....oo'),
            @(9, 'ommo..ommo'),
            @(9, 'ommo..ommo'),
            @(9, 'osso..osso'),
            @(9, 'osso..osso'),
            @(8, 'occcooocccco'),
            @(7, 'occcccccccccco'),
            @(6, 'occcscececccccbo'),
            @(5, 'occcssxccccccccbbo'),
            @(5, 'occcccacccccccccbo'),
            @(6, 'occcccccccccbo'),
            @(8, 'oocccccccboo'),
            @(10, 'occcccccbo'),
            @(9, 'occcccccccccbo'),
            @(8, 'occcccccccccccccbo'),
            @(7, 'occcccccccccccccccccbo'),
            @(4, 'occcccccccccccccccccccbooo'),
            @(4, 'occcccccccccccccccccccosso'),
            @(4, 'occcccccccccccccccccccosso'),
            @(5, 'occcccccccccccccccccccsoo'),
            @(8, 'occccccccccccccccccco'),
            @(9, 'occcccccccccccccccco'),
            @(10, 'occcccccccccccccco'),
            @(10, 'occcccccccccccco'),
            @(9, 'occcccoocccccco'),
            @(8, 'occccco..occccco'),
            @(9, 'occco....occco'),
            @(9, 'oao......oao'),
            @(8, 'oosso....oosso')
        ) }

        # Hamster: brown spotted egg and compact cheek-heavy body. The wheel is
        # deliberately habitat furniture, never part of the draggable model.
        'hamster/0' { return New-ReferenceRows 30 @(
            @(12, 'oooooo'),
            @(10, 'oobbbbbboo'),
            @(9, 'obbbbbbbbbbo'),
            @(8, 'obbbbssbbbbbo'),
            @(7, 'obbbbssssbbbbbo'),
            @(6, 'obbbbbbbbbbbbbbo'),
            @(6, 'obbbbabbbbbabbbbo'),
            @(5, 'obbbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbaaabbaaabbbbo'),
            @(5, 'obbbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbsssbbbbbbbo'),
            @(6, 'obbbabbbbbbbabbbbo'),
            @(6, 'obbbbbbbbbbbbbbo'),
            @(7, 'obbbbbbbbbbbbo'),
            @(8, 'obbbbbbbbbbo'),
            @(9, 'oobbbbbbboo'),
            @(11, 'oooooooo')
        ) }
        'hamster/1' { return New-ReferenceRows 30 @(
            @(9, 'ooo...ooo'),
            @(8, 'obbo..obbo'),
            @(7, 'obbbbbbbbbo'),
            @(6, 'obbccececcbbbo'),
            @(5, 'obbbcccaccccbbbbo'),
            @(4, 'obbbbccmmmmccbbbbbo'),
            @(3, 'obbbbbbccccbbbbbbbbbo'),
            @(3, 'obbbbbbbbbbbbbbbbbbbo'),
            @(4, 'obbbbccccccccbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbo'),
            @(6, 'obbbbbbbbbbbbo'),
            @(7, 'obbboobbbbbo'),
            @(8, 'obbo..obbbo'),
            @(8, 'oao....oao')
        ) }
        'hamster/2' { return New-ReferenceRows 30 @(
            @(10, 'ooo.....ooo'),
            @(9, 'obbo.....obbo'),
            @(8, 'obbbbbbbbbbbbo'),
            @(7, 'obbbbssssbbbbo'),
            @(6, 'obbbssbbbbssbbbbo'),
            @(5, 'obbbbcecccebbbbbo'),
            @(4, 'obbbbcccaccccbbbbbo'),
            @(3, 'obbbbbccmmmmccbbbbbbo'),
            @(2, 'obbbbbbccccccbbbbbbbbo'),
            @(1, 'obbbbbbbbbbbbbbbbbbbbbo'),
            @(1, 'obbbbbbccccccccbbbbbbbo'),
            @(1, 'obbbbbccccccccccbbbbbbo'),
            @(1, 'obbbbbccccccccccbbbbbbo'),
            @(2, 'obbbbbccccccccbbbbbbbo'),
            @(2, 'obbbbbbbbbbbbbbbbbbbbo'),
            @(3, 'obbbbbbbbbbbbbbbbbbo'),
            @(4, 'obbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbboobbbbbo'),
            @(6, 'obbbbo..obbbbo'),
            @(7, 'obbbo....obbbo'),
            @(7, 'oosso....oosso')
        ) }
        'hamster/3' { return New-ReferenceRows 30 @(
            @(10, 'ooo.....ooo'),
            @(9, 'obbo.....obbo'),
            @(8, 'obbbbbbbbbbbbo'),
            @(7, 'obbbbssssbbbbo'),
            @(6, 'obbbssbbbbssbbbbo'),
            @(5, 'obbbbcecccebbbbbo'),
            @(4, 'obbbbcccaccccbbbbbo'),
            @(3, 'obbbbbccmmmmccbbbbbbo'),
            @(2, 'obbbbbbccccccbbbbbbbbo'),
            @(1, 'obbbbbbbbbbbbbbbbbbbbbo'),
            @(1, 'obbbbbbccccccccbbbbbbbo'),
            @(1, 'obbbbbccccccccccbbbbbbo'),
            @(1, 'obbbbbccccccccccbbbbbbo'),
            @(2, 'obbbbbccccccccbbbbbbbo'),
            @(2, 'obbbbbbbbbbbbbbbbbbbbo'),
            @(3, 'obbbbbbbbbbbbbbbbbbo'),
            @(4, 'obbbbbbbbbbbbbbbbo'),
            @(5, 'obbbbbbbbbbbbbbo'),
            @(6, 'obbbbboobbbbbo'),
            @(6, 'obbbbboobbbbbo'),
            @(7, 'obbbbo..obbbbo'),
            @(7, 'obbo....obbo'),
            @(6, 'oosssso..osssso'),
            @(7, 'oooooo....oooooo')
        ) }
        default { throw "Missing reference pixel master for $key" }
    }
}
