param(
    [string]$SourceDirectory = (Join-Path $PSScriptRoot "v3"),
    [string]$PreviewPath = ""
)

$ErrorActionPreference = "Stop"
$requestedPreviewPath = $PreviewPath

# Keep the v1 writer, frame index contract, and anchor serializer intact.
# V2 replaces the core adult cells with hand-maintained pixel stencils.
. (Join-Path $PSScriptRoot "redraw_adult_master_v1.ps1") -SourceDirectory $SourceDirectory
$PreviewPath = $requestedPreviewPath

$v2ColorCodes = @{
    o = 1; b = 2; s = 3; c = 4; h = 5; a = 6; m = 7; r = 8; e = 9; x = 10
}

function New-V2Art { @{} }

function Set-V2Pixel([hashtable]$art, [int]$x, [int]$y, [int]$color) {
    if ($x -ge 0 -and $x -lt 32 -and $y -ge 0 -and $y -lt 32) {
        $art["$x,$y"] = $color
    }
}

function Clear-V2Pixel([hashtable]$art, [int]$x, [int]$y) {
    [void]$art.Remove("$x,$y")
}

function Draw-V2Line([hashtable]$art, [int]$x0, [int]$y0, [int]$x1, [int]$y1, [int]$color) {
    $steps = [Math]::Max([Math]::Abs($x1 - $x0), [Math]::Abs($y1 - $y0))
    for ($step = 0; $step -le $steps; $step++) {
        $fraction = if ($steps -eq 0) { 0.0 } else { $step / [double]$steps }
        Set-V2Pixel $art ([Math]::Round($x0 + ($x1 - $x0) * $fraction)) ([Math]::Round($y0 + ($y1 - $y0) * $fraction)) $color
    }
}

function Paint-V2Stencil([hashtable]$art, [string]$source, [int]$originX = 3, [int]$originY = 15) {
    $rows = $source.Trim().Split("`n") | ForEach-Object { $_.TrimEnd("`r") }
    if ($rows.Count -gt 29 -or ($rows | Measure-Object Length -Maximum).Maximum -gt 26) {
        throw "Adult master stencil exceeds its 26x29 canvas"
    }
    for ($y = 0; $y -lt $rows.Count; $y++) {
        $row = $rows[$y]
        for ($x = 0; $x -lt $row.Length; $x++) {
            $code = $v2ColorCodes[$row[$x].ToString()]
            if ($null -ne $code) { Set-V2Pixel $art ($originX + $x) ($originY + $y) $code }
        }
    }
}

function Get-V2PixelPriority([int]$color) {
    switch ($color) {
        1 { return 100 } # Outline must survive a scale collision.
        9 { return 90 }
        10 { return 90 }
        6 { return 80 }
        5 { return 70 }
        4 { return 60 }
        3 { return 50 }
        default { return 40 }
    }
}

function Expand-V2Art([hashtable]$art) {
    $expanded = New-V2Art
    foreach ($cell in $art.GetEnumerator()) {
        $point = $cell.Key.Split(',')
        $x = [int]$point[0]
        $y = [int]$point[1]
        # Expand from the atlas pivot and preserve the authored foot baseline.
        $targetX = [Math]::Round(16 + ($x - 16) * 1.35)
        $targetY = [Math]::Round(29 + ($y - 29) * 1.12)
        $key = "$targetX,$targetY"
        if (-not $expanded.ContainsKey($key) -or (Get-V2PixelPriority $cell.Value) -ge (Get-V2PixelPriority $expanded[$key])) {
            Set-V2Pixel $expanded $targetX $targetY ([int]$cell.Value)
        }
    }
    return $expanded
}

function Mirror-V2Art([hashtable]$art) {
    $result = New-V2Art
    foreach ($cell in $art.GetEnumerator()) {
        $point = $cell.Key.Split(',')
        Set-V2Pixel $result (31 - [int]$point[0]) ([int]$point[1]) ([int]$cell.Value)
    }
    return $result
}

# Every stencil is intentionally authored as fixed pixels rather than assembled
# from circles or scale transforms. The front pose uses a light three-quarter
# asymmetry so a stationary pet reads as a character, not an app icon.
$v2Stencils = @{
    cat = @{
        front = @'
.......o....o.........
......obo..obbo........
......obbo.obbo........
.....obbbbbbbbbo.......
.....obbheebhbbo.......
.....obbbccbbbbo.......
....obbbbacabbbbo......
....obbbbbbbbbbbbo.....
.....obbbssssbbbbo.....
.....obbbccccbbbbo.....
......obbbbbbbbbo......
.......obbbbbbo........
......obb....obbo......
......ob......ob.......
......oo......oo.......
'@
        side = @'
..........oo............
........oobbo...........
.......obbbbo...........
......obhebbbbo..........
.....obbbccbbbbo.........
....obbbbbbbbbbo.........
....obbbssssbbbbo........
.....obbbccccbbbbo.......
......obbbbbbbbbbo.......
.......obbbbbbbbbo.......
........obbbbbbbbo.......
.........obb....obbo.....
..........ob.....ob......
..........oo.....oo......
'@
        back = @'
.......o....o.........
......obo..obbo........
......obbbbbbbbbo......
.....obbbbbbbbbbbo.....
.....obbbssssbbbbo.....
....obbbbbbbbbbbbbo....
....obbbssssssbbbbo....
.....obbbbbbbbbbbbo....
......obbbbbbbbbo......
......obb......obbo....
......ob........ob.....
......oo........oo.....
'@
        sleep = @'
.........................
.......oooo..............
.....oobbbboo............
....obbbcccbbbo..........
...obbbssssbbbbo.........
...obbbccccbbbbo.........
....obbbbbbbbbo..........
.....obbbbbbo............
......ooooo...oooo.......
..............obbo.......
...............oo........
'@
    }
    dog = @{
        front = @'
.....oo........oo.......
....obbo......obbo......
....obbo......obbo......
.....obbbbbbbbbo........
....obbbheebbbbo........
....obbbccccbbbbo.......
...obbbbccxccbbbbo......
...obbbbbbbbbbbbbo......
....obbbssssbbbbo.......
....obbbccccbbbbo.......
.....obbbbbbbbbo........
......obbbbbbo..........
.....obb....obbo........
.....ob......ob.........
.....oo......oo.........
'@
        side = @'
.........oooo............
........obbbbo...........
........obbbbo...........
......oobhebbbbo..........
.....obbbccccbbbbo........
....obbbccxxcbbbbo........
....obbbbbbbbbbbbbo.......
.....obbbssssbbbbo........
......obbbccccbbbbo.......
.......obbbbbbbbbbo......
........obbbbbbbbbo......
.........obb....obbo.....
..........ob.....ob......
..........oo.....oo......
'@
        back = @'
.....oo........oo.......
....obbo......obbo......
.....obbbbbbbbbo........
....obbbbbbbbbbbo.......
...obbbssssssbbbbo......
...obbbbbbbbbbbbbo......
....obbbssssbbbbo.......
.....obbbbbbbbbo........
......obbbbbbo..........
.....obb......obbo......
.....ob........ob.......
.....oo........oo.......
'@
        sleep = @'
.........................
......oooo...............
....oobbbboo.............
...obbbccccbbbo..........
...obbbssssbbbbo.........
....obbbbbbbbbo..........
.....obbbbbbo............
......obbo...oooo........
.......oo....obbo........
...............oo........
'@
    }
    bird = @{
        front = @'
..........oo............
........oobboo..........
.......obheebbo.........
.......obbccbbbo........
......obbbbbbbbbo.......
.....obbbbbbbbbbbo......
....obbbccccccbbbbo.....
....obbbccccccbbbbo.....
....obbbssssssbbbbo.....
.....obbbccccbbbbo......
......obbbbbbbbbo.......
......obbb..bbbbo.......
.......oo....oo.........
'@
        side = @'
..........oo............
........oobbbo..........
......oobhebbbbo.........
.....aobbbccbbbbo........
......obbbbbbbbbbo.......
.......obbbccccbbbbo.....
........obbbccccbbbbo....
.........obbbssssbbbbo...
..........obbbccccbbbo...
...........obbbbbbbbo....
...........obbb..bbbo....
............oo....oo.....
'@
        back = @'
..........oo............
........oobbbo..........
.......obbbbbbo.........
......obbbbbbbbbo.......
.....obbbssssbbbbo......
....obbbssssssbbbbo.....
....obbbbbbbbbbbbbo.....
.....obbbssssbbbbo......
......obbbbbbbbbo.......
.......obbb..bbbo.......
........oo....oo........
'@
        sleep = @'
.........................
.........ooo.............
......ooobbbboo..........
....obbbccccbbbbo........
....obbbssssbbbbo........
.....obbbbbbbbbo.........
......obbbbbbbo..........
.......oooooo............
...........oo............
'@
    }
    rabbit = @{
        front = @'
.......oo....oo.........
......obbo..obbo........
......obbo..obbo........
......obbo..obbo........
......obbbbbbbbbo.......
.....obbbheebbbbo.......
.....obbbccccbbbbo......
....obbbbbbbbbbbbbo.....
....obbbssssssbbbbo.....
.....obbbccccbbbbo......
......obbbbbbbbbo.......
......obb..bb..obbo.....
......ob........ob......
......oo........oo......
'@
        side = @'
..........oo............
.........obbo...........
.........obbo...........
.........obbo...........
.......oobhebbbbo........
......obbbccccbbbbo......
.....obbbbbbbbbbbbbo.....
......obbbssssbbbbo......
.......obbbccccbbbbo.....
........obbbbbbbbbbo....
.........obbbbbbbbbo....
..........obb...obbo....
...........ob....ob.....
...........oo....oo.....
'@
        back = @'
.......oo....oo.........
......obbo..obbo........
......obbo..obbo........
......obbbbbbbbbo.......
.....obbbbbbbbbbbo......
....obbbssssssbbbbo.....
....obbbbbbbbbbbbbo.....
.....obbbssssbbbbo......
......obbbbbbbbbo.......
......obb......obbo.....
......ob........ob......
......oo........oo......
'@
        sleep = @'
.........................
.......oo................
.......obbo..............
.....oobbbbboo...........
....obbbccccbbbbo........
....obbbssssbbbbo........
.....obbbbbbbbbo.........
......obbbbbbo...........
.......oooooo............
'@
    }
    penguin = @{
        front = @'
.........oooo............
........obbbbo...........
.......obheebbo..........
.......obbccbbbo.........
......obbbbbbbbbo........
......obbbccccbbbo.......
.....obbbbccccbbbbo......
.....obbbccccccbbbbo.....
.....obbbssssssbbbbo.....
......obbbccccbbbbo......
.......obbbbbbbbbo.......
.......obbb..bbbbo.......
........aa....aa.........
'@
        side = @'
..........oooo...........
.........obbbbo..........
.......aobhebbbbo.........
........obbbccbbbo........
........obbbbccccbbo......
.........obbbbccccbbbo....
.........obbbssssbbbbo....
..........obbbccccbbbbo...
...........obbbbbbbbbo....
............obbb..bbbo...
.............aa....aa.....
'@
        back = @'
.........oooo............
........obbbbo...........
.......obbbbbbo..........
......obbbbbbbbbo........
.....obbbssssbbbbo.......
.....obbbssssssbbbbo.....
.....obbbbbbbbbbbbbo.....
......obbbssssbbbbo......
.......obbbbbbbbbo.......
.......obbb..bbbbo.......
........aa....aa.........
'@
        sleep = @'
.........................
........oooo.............
......oobbbboo...........
....obbbccccbbbbo........
....obbbssssbbbbo........
.....obbbccccbbbo........
......obbbbbbbbo.........
.......obbbbbo...........
........aa..aa...........
'@
    }
}

function Get-V2Stencil([string]$species, [string]$view) {
    $value = $v2Stencils[$species][$view]
    if ([string]::IsNullOrWhiteSpace($value)) { throw "Missing V2 stencil: $species/$view" }
    return $value
}

function Draw-V2IdleDetail([hashtable]$art, [string]$species, [int]$facing, [int]$frame) {
    $rhythm = @(0, 1, 2, 1, 0, -1, -2, -1)[$frame % 8]
    switch ($species) {
        "cat" {
            $origin = if ($facing -eq 2) { 25 } elseif ($facing -eq 3) { 6 } else { 25 }
            Draw-V2Line $art $origin 22 ($origin + [Math]::Sign($rhythm) * 2) (19 - [Math]::Abs($rhythm)) 1
            Set-V2Pixel $art ($origin + [Math]::Sign($rhythm) * 2) (19 - [Math]::Abs($rhythm)) 2
        }
        "dog" {
            $origin = if ($facing -eq 2) { 26 } elseif ($facing -eq 3) { 5 } else { 25 }
            Draw-V2Line $art $origin 24 ($origin + [Math]::Sign($rhythm) * 2) (24 + $rhythm) 1
            Set-V2Pixel $art ($origin + [Math]::Sign($rhythm) * 2) (24 + $rhythm) 2
        }
        "bird" {
            $wingY = 20 + $rhythm
            Draw-V2Line $art 10 21 6 $wingY 1
            Draw-V2Line $art 22 21 26 (20 - $rhythm) 1
            Set-V2Pixel $art 6 $wingY 3
            Set-V2Pixel $art 26 (20 - $rhythm) 3
        }
        "rabbit" {
            $earSweep = @(-3, -2, -1, 0, 1, 2, 3, 2)[$frame % 8]
            Draw-V2Line $art 11 20 (11 + $earSweep) (15 + [Math]::Abs($earSweep % 2)) 1
            Draw-V2Line $art 21 20 (21 - $earSweep) (15 + [Math]::Abs($earSweep % 2)) 1
        }
        "penguin" {
            Draw-V2Line $art 10 20 7 (22 + $rhythm) 1
            Draw-V2Line $art 22 20 25 (22 - $rhythm) 1
        }
    }
}

function Draw-V2WalkDetail([hashtable]$art, [string]$species, [int]$facing, [int]$frame) {
    $stride = @(-3, -2, -1, 1, 3, 2, 1, -1, -3, -2)[$frame]
    $lead = [Math]::Sign($stride)
    $cadence = @(-4, -3, -2, -1, 0, 1, 2, 3, 4, 3)[$frame]
    if ($species -in @("bird", "penguin")) {
        Set-V2Pixel $art (12 + $lead) (29 - [Math]::Abs([Math]::Min(0, $stride))) 6
        Set-V2Pixel $art (19 + $lead) (29 - [Math]::Abs([Math]::Max(0, $stride))) 6
    } else {
        Draw-V2Line $art 12 27 (10 + $lead * 2) (29 - [Math]::Abs([Math]::Min(0, $stride))) 1
        Draw-V2Line $art 20 27 (22 + $lead * 2) (29 - [Math]::Abs([Math]::Max(0, $stride))) 1
    }
    switch ($species) {
        "cat" { Draw-V2Line $art 24 22 (27 - $lead) (20 - [Math]::Abs($stride)) 1 }
        "dog" { Draw-V2Line $art 25 24 (28 - $lead) (25 + $lead) 1 }
        "bird" {
            Draw-V2Line $art 10 21 (6 + $cadence) (24 - [Math]::Abs($cadence % 3)) 1
            Set-V2Pixel $art (7 + $cadence) (24 - [Math]::Abs($cadence % 3)) 3
        }
        "rabbit" { Draw-V2Line $art 11 10 (9 + $lead) (5 + [Math]::Abs($stride)) 1 }
        "penguin" {
            Draw-V2Line $art 10 20 (6 + $cadence) (24 - [Math]::Abs($cadence % 3)) 1
            Draw-V2Line $art 22 20 (26 - $cadence) (24 - [Math]::Abs($cadence % 2)) 1
            Set-V2Pixel $art (7 + $cadence) (24 - [Math]::Abs($cadence % 3)) 3
            Set-V2Pixel $art (25 - $cadence) (24 - [Math]::Abs($cadence % 2)) 3
        }
    }
}

function Draw-V2EatingDetail([hashtable]$art, [string]$species, [int]$facing, [int]$frame) {
    $reach = @(-4, -3, -2, -1, 0, 1, 2, 3, 4, 3)[$frame]
    $mouthX = if ($facing -eq 2) { 9 } elseif ($facing -eq 3) { 22 } else { 17 }
    $direction = if ($facing -eq 3) { 1 } else { -1 }
    # Food travels through eight exterior positions into the beak/paw. Keeping
    # it outside the broad adult silhouette preserves the action at card scale.
    $foodX = if ($facing -eq 3) { 30 - $frame } else { 1 + $frame }
    $foodY = @(19, 18, 17, 16, 15, 14, 13, 12, 13, 14)[$frame]
    Set-V2Pixel $art $foodX $foodY 6
    Set-V2Pixel $art ($foodX + $direction) $foodY 5
    Draw-V2Line $art (16 + $direction * ($frame % 2)) 24 $foodX ($foodY + 1) 4
    # The feeding limb follows the food in a full reach-and-return cycle.
    # This keeps the motion readable after 32px integer scaling.
    $handBaseX = if ($species -in @("bird", "penguin")) { 18 } else { 17 }
    $handBaseY = if ($species -eq "penguin") { 24 } else { 25 }
    Draw-V2Line $art $handBaseX $handBaseY ($handBaseX + $reach) (20 + [Math]::Abs($reach % 3)) 1
    Set-V2Pixel $art ($handBaseX + $reach) (20 + [Math]::Abs($reach % 3)) 3
    if ($species -eq "bird") { Set-V2Pixel $art ($mouthX + $direction) 15 6 }
}

function Draw-V2SleepDetail([hashtable]$art, [string]$species, [int]$facing, [int]$frame) {
    $dreamX = if ($facing -eq 2) { 19 } elseif ($facing -eq 3) { 9 } else { 23 }
    $dreamY = 15 - [Math]::Floor($frame / 2)
    $breath = @(0, 1, 2, 3, 2, 1, 0, -1, -2, -1)[$frame]
    Set-V2Pixel $art $dreamX $dreamY 5
    Set-V2Pixel $art ($dreamX + 1) ($dreamY - 1) 5
    if ($frame % 3 -eq 0) { Set-V2Pixel $art ($dreamX + 2) ($dreamY - 2) 5 }
    # A sleeping pose still moves its body: this is a breathing limb/tail cycle,
    # not a decorative particle animation.
    switch ($species) {
        "cat" { Draw-V2Line $art 21 25 (24 + $breath) (25 - [Math]::Abs($breath % 2)) 1 }
        "dog" { Draw-V2Line $art 20 25 (24 + $breath) (26 - [Math]::Abs($breath % 2)) 1 }
        "bird" { Draw-V2Line $art 13 24 (10 + $breath) (25 - [Math]::Abs($breath % 2)) 1 }
        "rabbit" { Draw-V2Line $art 12 22 (10 + $breath) (19 - [Math]::Abs($breath % 2)) 1 }
        "penguin" { Draw-V2Line $art 13 25 (10 + $breath) (26 - [Math]::Abs($breath % 2)) 1 }
    }
}

function Draw-AdultFrame([string]$species, [int]$action, [int]$facing, [int]$frame) {
    $art = New-V2Art
    if ($facing -eq 3) {
        $art = Draw-AdultFrame $species $action 2 $frame
        return Mirror-V2Art $art
    }
    $view = if ($action -eq 4) { "sleep" } elseif ($facing -eq 0) { "front" } elseif ($facing -eq 1) { "back" } else { "side" }
    Paint-V2Stencil $art (Get-V2Stencil $species $view)
    switch ($action) {
        0 { Draw-V2IdleDetail $art $species $facing $frame }
        1 { Draw-V2WalkDetail $art $species $facing $frame }
        2 { Draw-V2EatingDetail $art $species $facing $frame }
        4 { Draw-V2SleepDetail $art $species $facing $frame }
    }
    return Expand-V2Art $art
}

foreach ($species in $speciesNames) {
    $imagePath = Join-Path $SourceDirectory "$species.png"
    $anchorsPath = Join-Path $SourceDirectory "$species.anchors.json"
    $bytes = Load-BitmapBytes $imagePath
    $anchors = @(Get-Content -Raw -LiteralPath $anchorsPath | ConvertFrom-Json)
    foreach ($action in $coreActions) {
        for ($facing = 0; $facing -lt 4; $facing++) {
            for ($frame = 0; $frame -lt $actionFrameCounts[$action]; $frame++) {
                $art = Draw-AdultFrame $species $action $facing $frame
                $index = Get-FrameIndex $action $facing $frame
                Write-Art $bytes $index $art
                $frameAnchors = Get-AdultAnchors $art $species $action $facing $frame
                if ($action -eq 4) {
                    $sleepHandShift = @(-2, -1, 0, 1, 2, 1, 0, -1, -2, -1)[$frame]
                    $frameAnchors.hand[0] = Clamp-Grid ($frameAnchors.hand[0] + $sleepHandShift)
                    $frameAnchors.hand[1] = Clamp-Grid ($frameAnchors.hand[1] - [Math]::Abs($sleepHandShift % 2))
                }
                $anchors[$index] = [PSCustomObject]@{
                    index = $index
                    anchors = $frameAnchors
                }
            }
        }
    }
    Save-BitmapBytes $imagePath $bytes
    [System.IO.File]::WriteAllText($anchorsPath, ($anchors | ConvertTo-Json -Depth 5), [System.Text.UTF8Encoding]::new($false))
    Write-Output "Redrew adult master v2 for $species"
}

if (-not [string]::IsNullOrWhiteSpace($PreviewPath)) { Write-Preview $PreviewPath }
Write-Output "Adult master v2 redraw completed"
